### ISSUE TITLE
ToDo #9

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#10]
## @peaceRyun 오늘의 목표
- [ ] tdlregister => 데이터 우선순위에 맞게 나오게 해보기 
- [x] tdlregister => Step2 이전과 다음 버튼 absolute으로 띄워서 더 큰화면에도 깨지지 않게 하기
- [ ] mukkitlist => api 끌어오고 가공해서 데이터 던져보기 
- [x] mukkitlist => foodlist 각각 사이즈 키워보기(width값만 늘리면 됨) 
---
## 오늘 한 일

> 오전 (9:30~12:00)

> 오후 (12:00~18:00)
- tdlregister => 이전과 다음버튼 fixed로 고정, Step2 그래프 반응형 고정 추가
- mukkitlist => foodlist 각각 사이즈 키워보기(width값만 늘리면 됨)
