### ISSUE TITLE
ToDo #10

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#11]
## @peaceRyun 오늘의 목표
- [ ] home => '스트레스를 날립시다!' 라는 문구를 넣어서 개성을 넣어보자!
- [ ] tdlregister => 데이터 우선순위에 맞게 나오게 해보기 
- [ ] mukkitlist => api 끌어오고 가공해서 데이터 던져보기 
- [x] mukkitlist => ui 꾸며보기 + 초코렛, 사과 개별 크기 줄이기, 버섯 amber가 무슨 색인지 찾아보기
- [x] 전체적으로 반응형 체크하고 화면이 달라지는 부분이 있다면 수정하기
---
## 오늘 한 일

> 오전 (9:30~12:00)
- diary => 레이아웃 수정1(image 너비 100퍼) // header => 레이아웃 수정1(너비 390px 고정, right 삭제, 중앙정렬)
- 마이너 이슈 수정1
- mukkitlist => foodlist ui 수정1
- mukkitlist => foodlist ui 수정2(버섯 배경 색깔 변경, search 리디자인)

> 오후 (12:00~18:00)
- mukkitlist => 중복 컴포넌트 삭제 + 감정 별 다른 페이지 나오게 하기 + header가 depth별 다르게 나오게 하기
- 마이너 이슈 수정2('보수중' 화면 추가)
- encyclopedia => 중복 레이아웃 수정 + maldigestion, musclepain 페이지 추가
- 마이너 이슈 수정3(보수중 화면 문구 추가, 먹킷 list 글꼴 변경)
- animate 패키지 설치 // home => 디스플레이 문구 추가
- footer => 반응형 수정

**Comment by peaceRyun** [comment]
## 반응형을 고치기 위해서 유념해야하는 사실
- 이미지는 항상 100%로 조절하는 것이 좋다.

```
import Image from 'next/image';

                <Image
                    src='/images/pattern/main/main-bg1.png'
                    alt='bg1'
                    width={390}
                    height={180}
                    className='w-full opacity-50'
                />

//Image태그의 경우, width값을 반드시 줘야 하므로 tailwind로 다시 w-full을 준다.

```

- 레이아웃은 항상 가장 바깥쪽에 있는 부모에게 relative를 먹여서 절대px를 줘서 고정 시키는 것이 좋고, 아이들에게는 100%를 주는 것이 반응형 제어에 도움이 된다.

**Comment by peaceRyun** [comment]
## 코드 이해

```    
const segments = useSelectedLayoutSegments();
const isNewDiaryPage = segments.includes('newdiary');
if (isNewDiaryPage) {
    return <>{children}</>;
}
```
useSelectedLayoutSegments는 Next.js의 네비게이션 훅으로, 현재 URL의 경로 세그먼트들을 배열로 반환합니다. 예를 들어 URL이 /diary/diaryunlocked/newdiary라면 ['diary', 'diaryunlocked', 'newdiary']와 같이 반환됩니다.
여기서 isNewDiaryPage는 현재 URL에 'newdiary' 세그먼트가 포함되어 있는지 확인하는 boolean 값입니다.
