### ISSUE TITLE
ToDo #11

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#12]
## @peaceRyun 오늘의 목표
- [ ] home => '스트레스를 날립시다!' 라는 문구를 넣어서 개성을 넣어보자!
- [ ] tdlregister => 데이터 우선순위에 맞게 나오게 해보기 
- [ ] mukkitlist => api 끌어오고 가공해서 데이터 던져보기 
- [ ] 피드백 대로 수정해보기
---
## 오늘 한 일

> 오전 (9:30~12:00)
- typescript 수업
- meta 수정

> 오후 (12:00~18:00)
- typescript 수업
- metadata 분리

> 저녁(18:00~22:00)
- home => 채도 올리기
- home => menu 아이콘 교체(3d->일러스트), 영어에서 한글로 교체
- footer => 투명화

**Comment by peaceRyun** [comment]
오전에 강사님 + 반동기분들에게 받은 1차 피드백

- [x] 버튼의 채도를 높여라
- [x] 중국게임 같다 => 아이콘을 3d를 쓰지말고 simple한 것을 써라
- [x] 아이콘의 크기를 다 맞춰라
- [x] display문구는 빼라
- [x] footer의 색깔을 배경색깔과 맞춰라
- [ ] 전광판 blur를 없애라
- [ ] 전광판 크기를 높여라
- [x] 개복치라는 단어를 한국어로 적어라
- [ ] 로딩화면과 같은 intro 페이지를 하나 만드는 것이 더 명확할 수 있다.
