### ISSUE TITLE
ToDo #12

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#13]
## @peaceRyun 오늘의 목표
- [ ] tdlregister => 데이터 우선순위에 맞게 나오게 해보기 
- [ ] mukkitlist => api 끌어오고 가공해서 데이터 던져보기 
- [ ] 피드백 대로 수정해보기
---
## 오늘 한 일

> 오전 (9:30~12:00)
- typescript 수업

> 오후 (12:00~18:00)
- typescript 수업
- home => IconSprite 생성
- home => menu 수정1
- home => 줄바꿈 수정

> 저녁(18:00~22:00)
- home => 아이콘 교체 시도 1
- footer => md 삭제

**Comment by peaceRyun** [comment]
오전에 강사님 + 반동기분들에게 받은 2차 피드백

- [ ] 전광판 blur를 없애라
- [ ] 전광판 크기를 높여라
- [ ] 로딩화면과 같은 intro 페이지를 하나 만드는 것이 더 명확할 수 있다.
- [ ] 색깔을 3개로 맞추고, 그라데이션을 넣어라.
- [x] pinterest에서 색조합을 검색해보라. 톤을 높인 것을 써라
- [x] 아이콘을 한페이지에 있는 것을 써보려고 노력하라(통일감)
- [x] 아이콘의 크기를 작게 만들어라

**Comment by peaceRyun** [comment]
![image](https://github.com/user-attachments/assets/4da43fd2-61e4-4587-a9db-7ddd45db276c)

**Comment by peaceRyun** [comment]
2차 피드백 1차 수정(아이콘만)

![image](https://github.com/user-attachments/assets/4da43fd2-61e4-4587-a9db-7ddd45db276c)

**Comment by peaceRyun** [comment]
2차 피드백 2차 수정안(버튼 배경 3색만, 그라디언트 적용O)
![image](https://github.com/user-attachments/assets/a73be586-12b6-4286-9abf-6ab79dfd1727)

**Comment by peaceRyun** [comment]
![image](https://github.com/user-attachments/assets/58f95664-9925-47cc-9ea5-caefb879966d)
