### ISSUE TITLE
ToDo #13

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#14]
## @peaceRyun 오늘의 목표
- [ ] tdlregister => 데이터 우선순위에 맞게 나오게 해보기 
- [ ] mukkitlist => api 끌어오고 가공해서 데이터 던져보기 
- [ ] 피드백 대로 수정해보기
---
## 오늘 한 일

> 오전 (9:30~12:00)
- typescript 수업

> 오후 (12:00~18:00)
- typescript 수업
- home => 아이콘 교체 시도 1
- home => 아이콘 교체 시도 2
- home => 아이콘 교체 시도 3 + 색상교체

> 저녁(18:00~22:00)
- mukkit => 요리리스트 페이지 구현1
- mukkit => api 끌어오기 //  classnames, axios 라이브러리 설치
- mukkit => api 끌어오기2

**Comment by peaceRyun** [comment]
## 메인화면 3차 수정

![image](https://github.com/user-attachments/assets/b3065d45-10e5-4f2a-9338-721ddb709373)
