### ISSUE TITLE
ToDo #3

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#4]
오늘 한 일

> 오전
- saddished => dropdown 구현1
- saddished => dropdown 구현2
- saddished => dropdown 구현3(a 태그 link태그로 바꾸기)

> 오후
- readme => 제작기간 추가 // 증상별백과사전 => 페이지 구현 1
- readme => 내용추가
- 증상별encyclopedia => 페이지 구현1
- home => 이번달 전광판 swiper 수정
- diary => 핀 비밀번호 구현1

---
오늘 할 일
- [x] 먹킷리스트 => depth 더 구현, api 끌어오는 방법 고민해보기
- [x] 증상별 백과사전 => 메인화면 디자인 레퍼런스 찾고 구현해보기
- [x] diary => 비밀번호 페이지 구현

**Comment by peaceRyun** [comment]
> ㅇㅇㅇ

**Comment by peaceRyun** [comment]
- API 끌어오는 방법을 내 repo "dashboard-study > news"에서 찾음. 
- 강사님 블로그도 참조하면 더 좋음(https://odada.me/309)
- 하지만 생각보다 복잡하여 나중에 하기로 함. 시간을 너무 많이 보낼 꺼 같음

**Comment by peaceRyun** [comment]
> 오늘 할 일
> 
> * [ ]  먹킷리스트 => depth 더 구현, api 끌어오는 방법 고민해보기


1. API 끌어오는 방법을 내 repo "dashboard-study > news"에서 찾음. 
2. 강사님 블로그도 참조하면 더 좋음(https://odada.me/309)
3. 하지만 생각보다 복잡하여 나중에 하기로 함. 시간을 너무 많이 보낼 꺼 같음
