### ISSUE TITLE
ToDo #6

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#7]
## 오늘의 목표
- [ ] 메인화면 색깔 더 쨍하게, 레퍼런스처럼 버튼 높이 더 낮게, 아이콘은 오른쪽, 띄우고, 튀어나오게 배치해보기 @peaceRyun 
- [ ] diary > newdiary mood 선택하는 모달창 구현, 캘린더 모달창 구현, 저장한 데이터 diaryunlocked에 던지기
- [ ] 전광판 padding 값 더 줘보기
---
## 오늘 한 일

> 오전 (9:30~12:00)
- home => 레이아웃 일부 수정, menu 버튼 grid 수정
- 이미지 편집, home => MainButton 컴포넌트 수정1(색상, 텍스트배치, 이미지 교체 및 배치)
- 이미지 편집, home => MainButton 컴포넌트 수정2(border 색상 약간 더 진하게)
- 취업지원 공고 살펴보기 30분(웹퍼블리셔/프론트엔드)

> 오후 (12:00~18:00)
- home => 전광판 폰트 수정1
- home => 전광판 폰트 수정2(색깔 변경)
- home => 전광판 내용 수정1(주별, 월별, 제목 삭제)
- 이미지 중복파일 삭제, diary => newdiary 모달창 구현1
- diary => newdiary 모달창 구현2
- diary => newdiary 모달창 구현3(위치 변경)
- diary => newdiary 모달창 구현4(usestate 사용하여 선택효과, map으로 반복 정리)
- diary => newdiary 모달창 구현5(date-fns 라이브러리 설치 및 CalendarModal 구현)
- diary => newdiary 태그 padding 조절
- diary => 마이너 수정 및 데이터 시도1(usecontext)
- diary => 데이터 시도2(usestate) // main => textunderline 삭제
- home => ledSwiper 높이 늘리고 텍스트 수직중앙정렬

**Comment by peaceRyun** [comment]
페이지마다 데이터를 던지기 위해서? useContext()를 이용해야 한다.

**Comment by peaceRyun** [comment]
useRouter를 통해 diary 데이터를 페이지간으로 던져보려다가 실패하였다.

-> 나중에 nodejs를 배우면서 더 배워볼 훅이다.
