### ISSUE TITLE
ToDO #7

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#8]
## 오늘의 목표
- [x] 저장 버튼 다르게 커스터마이징 해보기 @peaceRyun 
- [x] diary => 날짜와 감정도 다른 페이지에 전달할 수 있도록 구현하기 @peaceRyun 
- [ ] tdlregister => 전광판 등록 리디자인 및 데이터 던져보기 @peaceRyun 
- [ ] mukkitlist => API 연동해서 아코디언 형태로 데이터 나오게 해보기 @peaceRyun_ 
- [x] header => 390px로 고정시켜놓기 @peaceRyun 
- [x] versel에 베포해보기 @peaceRyun 
---
## 오늘 한 일

> 오전 (9:30~12:00)
- diary => newdiary 저장 버튼 커마1
- diary => newdiary 저장 버튼 커마2(폰트 크기 조절)
- header => type3 제작1 // diary=>router관련 코드 삭제
- diary => 감정 아이콘전달하여 생성1(NewDiary, MoodModal, DiaryUnlocked 코드 수정)
- diary => 날짜를 전달하여 생성2(DiaryUnlocked 코드 수정)
- diary => 날짜를 전달하여 생성3(NewDiary, CalendarModal 코드 수정)
- diary => 날짜를 전달하여 생성3(diaryunlocked, DiaryCard, CalendarModal 코드 수정)

> 오후 (12:00~18:00)
- Header => lg관련 삭제(반응형 삭제)
- 마이너 코드수정1
- tdlregister => step ui 디자인/로직 수정1(색깔, radio버튼 디자인, step3 로직 수정)
- tdlregister => step ui 디자인/로직 수정2(step3 완료버튼 로직 수정)
- 주석정리
- tdlregister => 전광판으로 데이터 던지기(step3 완료버튼 로직 수정)(오류 있음)
- tdlregister => 전광판으로 데이터 던지기2(step3 완료버튼 로직 수정, swiper 로직 수정)

**Comment by peaceRyun** [comment]
## @peaceRyun Issue

- [ ] header type3를 제작하여 화면을 늘리더라도 저장 버튼이 튀어나가지 않도록 하자.
-> type3를 만드는 형태는 handleSave라는 변수를 가져오기가 힘들어져 프로그래밍이 되지 않는다.

- [ ] MoodModal(자식컴포넌트)에 있는 감정과 fill값(usestate)을 NewDiaryPage(부모페이지)에 전달하고, NewDiaryPage(해당페이지)에서 로컬스토리지에 저장하는 코드에 변수로 추가하고 싶다.
-> 잘 안되고 있다. 감정을 전달하는 것 까지는 성공. but 날짜를 변경하고 저장되는 로직을 쓰니 mood에 null이 전달되면서 오류가 생김
-> DiaryCard에서 데이터값을 받지 않아서 생기는 오류였음. -> 해결.
-> 기분을 선택하지 않았을 때 생기는 오류는 여전히 있음.

> tdlregister => step ui 디자인/로직 수정1(색깔, radio버튼 디자인, step3 로직 수정)
- [x] tdlregister 버튼 디자인을 하면서 색상이 만족스럽지 않았음. -> adobe color에 '심해' 탐색 -> tailwind.config에 커마 컬러를 넣었음.
- [x] step3 마지막 단계에서 모든 값이 기입되어야 완료버튼이 활성화되도록 로직을 짰음
``<button
                            className={`px-4 py-2 rounded-md font-medium ${
                                currentStep === 2 && !(value && valueText && valueTitle)
                                    ? 'bg-gray-300 text-gray-600 cursor-not-allowed'
                                    : 'bg-custom-deepsea-500 text-white hover:bg-custom-deepsea-600'
                            }`}
                            onClick={handleNext}
                            disabled={
                                currentStep === 2 && !(value && valueText && valueTitle)
                            }
                        >
                            {currentStep === 2 ? '완료' : '다음'}
                        </button>``
