### ISSUE TITLE
ToDo #8

### ISSUE THREAD

**Issue by peaceRyun** [peaceRyun/sunfish2#9]
## @peaceRyun 오늘의 목표
- [x] tdlregister => 전광판 swiper vertical로 수정하기 
- [ ] tdlregister => 데이터 우선순위에 맞게 나오게 해보기 
- [x] tdlregister => 전광판 글자 제한 두기 
- [x] tdlregister => Step2 더 명확하게 하기(영어를 한글로) 
- [x] tdlregister => Step2 그래프 배경 넣기 
- [x] tdlregister => Step3 로직 수정하기(처음부터 빨간색이 나오지 않게, 마지막페이지에서는 자동으로 루트페이지로 오게 수정)
- [ ] tdlregister => Step2 이전과 다음 버튼 absolute으로 띄워서 더 큰화면에도 깨지지 않게 하기
- [x] tdlregister => Step3 왼쪽 정렬 되게 하기
- [x] home => 버튼들 크게 되지 않게 하기. 
- [x] mukkitlist => 아코디언 형태로 ui디자인 
- [ ] mukkitlist => api 끌어오고 가공해서 데이터 던져보기 
- [ ] mukkitlist => foodlist 각각 사이즈 키워보기(width값만 늘리면 됨) 
---
## 오늘 한 일

> 오전 (9:30~12:00)
- 강사님 오전 피드백(UI/UX 관련)
- home => ledBoardSwiper컴포넌트 수정(로딩중, 할없 레이아웃 수정, swiper 방향 수정, key 추가)
- home => 메뉴 버튼 hover효과 수정1
- home 불필요한 import삭제 // tdlregister => Step2 UI/UX 개선1

> 오후 (12:00~18:00)
- tdlregister => Step1, 2 코드 정리 + Step3 유효성검사 로직 수정
- tdlregister => Step2 그래프 배경 추가 및 폰트 크기 조절 + Step2 유효성검사 로직 수정
- tdlregister => Step3 내용 20자 제한 및 문구 추가
- mukkitlist => angry 데이터 관련 소스 추가
- mukkitlist => anxiety, tired 데이터 관련 소스 추가
- 강사님 오후 피드백(UI/UX 관련)
- tdlregister => 마이너 디자인 변경1

**Comment by peaceRyun** [comment]
# @peaceRyun 번외 목표

- [x] opensea 둘러보기

**Comment by peaceRyun** [comment]
# @peaceRyun 추가 학습

- useRadio() 훅 이해하기
 `{...input}`과 `{...checkbox}`가 어떤 속성들을 전달받는지 확인하기 위해 실제로 콘솔에 출력해보는 코드로 설명하겠습니다:



```javascript
const RadioCard = (props) => {
    const { getInputProps, getRadioProps } = useRadio(props);

    const input = getInputProps();
    const checkbox = getRadioProps();
    
    console.log('input props:', input);
    console.log('checkbox props:', checkbox);

    // ... rest of the component
}
```

실제로 전개되는 속성들은 다음과 같습니다:

`{...input}`이 전개하는 속성들:
- `type: "radio"` - input의 타입을 radio로 지정
- `name` - 라디오 그룹의 이름
- `value` - 해당 라디오 버튼의 값
- `onChange` - 변경 이벤트 핸들러
- `checked` - 선택 상태
- `aria-*` - 접근성 관련 속성들

`{...checkbox}`가 전개하는 속성들:
- `role: "radio"` - ARIA 역할 지정
- `aria-checked` - 현재 선택 상태
- `data-checked` - 선택 상태를 CSS에서 사용
- `data-state` - 현재 상태 정보
- `onClick` - 클릭 이벤트 핸들러
- `onKeyDown` - 키보드 이벤트 핸들러

이 속성들은 Chakra UI의 `useRadio` 훅이 자동으로 생성하여 제공하며, 라디오 버튼의 기본적인 동작과 접근성을 관리합니다. 전개 연산자를 사용함으로써 이러한 모든 필수 속성들을 한 번에 요소에 적용할 수 있습니다.

예를 들어, 다음과 같이 직접 작성하는 대신:
```javascript
<input 
  type="radio" 
  name={input.name}
  value={input.value}
  onChange={input.onChange}
  checked={input.checked}
  aria-checked={input.ariaChecked}
  // ... 더 많은 속성들
/>
```

간단히 `<input {...input} />`로 작성할 수 있습니다.

이러한 방식은 코드를 더 깔끔하게 만들고, Chakra UI가 제공하는 모든 기능과 접근성 속성들이 자동으로 적용되도록 해줍니다.
